version: '3'

services:
  app:
    build: .
    container_name: "app"
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  