version: '3'

services:
  app:
    build: .
    container_name: "app"
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  wiremock:
    image: wiremock/wiremock:latest
    container_name: "wiremock"
    ports:
      - 8080:8080
    volumes:
      - ./mappings:/home/wiremock/mappings
  